# KEYBINDS CONFIGURATION

# Global Keybinds
keymode=common
bind=SUPER+SHIFT,r,reload_config

# Default Keybinds - standard windows
keymode=default
bind=SUPER,q,killclient
bind=SUPER,return,toggle_named_scratchpad,none,kitty-main,kitty -T kitty-main # Terminal
bind=SUPER+SHIFT,return,spawn,kitty
bind=SUPER,e,toggle_named_scratchpad,dolphin,none,dolphin # File Manager
bind=SUPER,n,toggle_named_scratchpad,obsidian,none,obsidian # Notes App
bind=SUPER,f,togglemaximizescreen
bind=SUPER+SHIFT,f,togglefullscreen
bind=SUPER,t,togglefloating

bind=SUPER,a,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER,comma,spawn,qs -c noctalia-shell ipc call settings toggle

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_left,minimized
mousebind=SUPER+CTRL,btn_right,killclient
mousebind=SUPER+CTRL,btn_middle,togglefullscreen
mousebind=NONE,btn_middle,togglemaximizescreen,0

bind=SUPER,g,togglegaps
bind=SUPER,r,spawn_shell,mmsg -d setkeymode,resize | notify-send -a Mango -u low "Resize mode"

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Game Mode Binds 
keymode=gamer


# Resize Mode
keymode=resize
bind=NONE,Left,resizewin,-10,0
bind=NONE,Right,resizewin,+10,0
bind=NONE,ESCAPE,spawn_shell,mmsg -d setkeymode,default | notify-send -a Mango -u low "Default mode"
bind=SUPER,r,spawn_shell,mmsg -d setkeymode,default | notify-send -a Mango -u low "Default mode"
bind=SUPER+SHIFT,X,incgaps,1
bind=SUPER+SHIFT,Z,incgaps,-1

