# MONITORS CONFIG





# Steam Deck Monitor Flip
# monitorrule=name:^eDP-1$,custom:1,rr:3,width:800,height:1280,x:0,y:0,scale:1,refresh:59.999001
# monitorrule=name:^eDP-1$,rr:3
monitorrule=name:^eDP-1$,custom:1,width:800,height:1280,refresh:59.999001,y:0,x:0,rr:3

