# Window and Application Rules

# Tags / Workspaces
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# Terminal
windowrule=isnamedscratchpad:1,width:1280,height:800,title:kitty-main

# File manager
windowrule=isnamedscratchpad:1,width:1280,height:800,appid:dolphin

# Obsidian
windowrule=isnamedscratchpad:1,width:1350,height:850,appid:obsidian

# SISR
windowrule=isnamedscratchpad:1,open_as_floating:1,title:SISR

# # Noctalia Shell
# windowrule=isnoshadow:1,isnoblur:1,appid:notalia-shell
