# Main Configuration Files

xwayland_persistence=0
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100

focus_on_activate=1
sloppyfocus=1
warpcursor=1

focus_cross_monitor=0
focus_cross_tag=0

circle_layout=tile,scroller
enable_floating_snap=0
snap_distance=50

cursor_size=30
cursor_theme=Adwaita
cursor_hide_timeout=0
drag_tile_to_tile=1
single_scratchpad=0

# Touchscreen
touch_enable=1
touch_enable_mouse_emulation=0
touch_map_to_mon=^eDP-1$

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=1

# Source Subfiles Here
source=./main/animations.conf
source=./main/keybinds.conf
source=./main/monitors.conf
source=./main/windowrules.conf

exec-once=noctalia

# env=QT_QPA_PLATFORMTHEME,gtk3
# env=QT_QPA_PLATFORMTHEME_QT6,gtk3
env=QT_QPA_PLATFORMTHEME,qt6ct
# env=QT_QPA_PLATFORM=wayland
env=XDG_MENU_PREFIX,mango-

# This sources the noctalia theme



source=~/.config/mango/noctalia.conf
