# Main Configuration Files

xwayland_persistence=1
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100

focus_on_activate=1
sloppyfocus=1
warpcursor=1

focus_cross_monitor=0
focus_cross_tag=0

circle_layout=tile,scroller
enable_floating_snap=1
snap_distance=50

cursor_size=24
cursor_theme=Bibata-Modern-Ice
cursor_hide_timeout=0
drag_tile_to_tile=1
single_scratchpad = 1


# keyboard
repeat_rate=25
repeat_delay=600
numlockon=1

# Source Subfiles Here
source=./main/animations.conf
source=./main/keybinds.conf
source=./main/monitors.conf
source=./main/windowrules.conf

exec-once=qs -c noctalia-shell


# This sources the noctalia theme

source = /home/mark/.config/mango/noctalia.conf

